### ISSUE TITLE
Even if GlotPress generated language pack and push to the sites, this plugin cannot read them

### ISSUE THREAD

**Issue by alexclassroom** [WenPai-org/wpicp-license#1]
`$current_locale = get_locale();
if (!empty($current_locale)) {
    $mo_file = dirname(__FILE__) . '/languages/wpicp-license-' . $current_locale . ".mo";
    if (@file_exists($mo_file) && is_readable($mo_file)) {
        load_textdomain('wpicp-license', $mo_file);
    }
}`

The above code made this plugin cannot read the language pack file generated from GlotPress system, please check them.

After I commented on the above code, this plugin can read the MO file generated from GlotPress. The MO file generated from GlotPress always stores the default system path `/wp-content/languages/plugins`.

Don't only make your plugin read the MO file under `languages` folder on the plugin installation path.

I submitted a [PR](https://github.com/WenPai-org/wpicp-license/pull/2) for this I18N issue.

**Comment by wpbeian** [comment]
Thanks for reporting this bug, we will update the plugin.
